### PR TITLE
Fixed the overlapping of logo and home button

### LINKED ISSUE #61: Overlapping of Club LOGO and Home button.
On the <a href="https://dscvit.com/" target="_blank">Home page</a> of club website the logo and the Home button are overlapping in navbar.

Screenshot (281)_LI

### PR DESCRIPTION
**Pull request by manishkrjha**
This PR fixes #61

Added margin around the logo/image.

Signed-off-by: Manish Jha <codernibba@gmail.com>

### CODE REVIEW

**Comment by Nirmitjatana** [comment]
> This PR fixes #61
> 
> Added margin around the logo/image.
> 
> Signed-off-by: Manish Jha [codernibba@gmail.com](mailto:codernibba@gmail.com)

This won't fix the dark mode.

**Comment by Nirmitjatana** [comment]
> > This PR fixes #61
> > Added margin around the logo/image.
> > Signed-off-by: Manish Jha [codernibba@gmail.com](mailto:codernibba@gmail.com)
> 
> This won't fix the dark mode.

@manishkrjha

**Comment by manishkrjha** [comment]
> > This won't fix the dark mode.
> 
> @manishkrjha

Didn't noticed that, apologies.

Screenshot (289)

Screenshot (288)

Fixed the issue.

**Comment by Geek-ubaid** [comment]
@Nirmitjatana why this PR pending, have you verified the changes requested?

**Comment by Nirmitjatana** [comment]
> @Nirmitjatana why this PR pending, have you verified the changes requested?

didn't get the notif

**Pull request merged**
